spring:
  application:
    name: config-service

  cloud:
    config.server.git:
      uri: https://github.com/AyushBatham444/lovable-config-server
      username: AyushBathma444
      password:
      default-label: master

server.port: 8888

eureka.instance:
  hostname: localhost
  prefer-ip-address: true
  instance-id: ${spring.application.name}:${server.port}
